// src/features/admin/products/components/tabs/TabBasico.tsx
import { forwardRef, useImperativeHandle, useState, useCallback, useMemo } from 'react';
import type { TabBasicoProps } from '../components/types';
import {
  generateSlug,
  generateSkuSuggestion,
  getInlineFieldError,
  calculateNameQualityScore,
} from '../../../../utils/productFormUtils';
import { ValidationHelper, SkuSuggestion, SlugPreview } from '../components/ValidationHelper';

export type TabBasicoRef = {
    validate: () => Record<string, string>;
};
import styles from '../AdminProductForm.module.css';

export const TabBasico = forwardRef<TabBasicoRef, TabBasicoProps>(function TabBasico({
    form,
    errors = {},
    setField,
    tagInput,
    setTagInput,
    featureInput,
    setFeatureInput,
    onAddTag,
    onRemoveTag,
    onAddFeature,
    onRemoveFeature,
}, ref) {
    const [localErrors, setLocalErrors] = useState<Record<string, string>>(errors);
    const [touched, setTouched] = useState<Record<string, boolean>>({});
    const [showSkuSuggestion, setShowSkuSuggestion] = useState(false);
    const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);

    useImperativeHandle(ref, () => ({
        validate: () => {
            const errs: Record<string, string> = {};
            if (!form.name.trim()) errs.name = 'El nombre es obligatorio';
            setLocalErrors(errs);
            return errs;
        }
    }), [form]);

    // Auto-GenErate slug cuando cambia el nombre (solo si está vacío o fue auto-generado)
    const handleNameChange = useCallback((newName: string) => {
        setField('name', newName);
        validateField('name', newName);

        // Auto-generar slug si está acío o si el usuario aún no lo ha modificado
        if (!form.slug || !touched.slug) {
          const autoSlug = generateSlug(newName);
          setField('slug', autoSlug);
        }

        // Auto-generar SKU sugerido
        if (!skuAutoGenerated && newName.trim()) {
          setShowSkuSuggestion(true);
        }
    }, [form.slug, skuAutoGenerated, touched.slug, setField]);

    // Validación inline
    const validateField = useCallback((fieldName: string, value: unknown) => {
        const error = getInlineFieldError(value, fieldName);
        setLocalErrors(prev => {
            if (error) {
                return { ...prev, [fieldName]: error };
            }
            const next = { ...prev };
            delete next[fieldName];
            return next;
        });
    }, []);

    const handleBlur = useCallback((fieldName: string) => {
        setTouched(prev => ({ ...prev, [fieldName]: true }));
    }, []);

    // Generar SKU sugerido
    const suggestedSku = useMemo(
        () => generateSkuSuggestion(form.name, form.category?.name || 'PROD'),
        [form.name, form.category?.name]
    );

    // Calcular score de calidad del nombre
    const nameQualityScore = useMemo(
        () => calculateNameQualityScore(form.name),
        [form.name]
    );

    const handleAcceptSuggestion = useCallback(() => {
        setField('sku', suggestedSku);
        setSkuAutoGenerated(true);
        setShowSkuSuggestion(false);
        validateField('sku', suggestedSku);
    }, [suggestedSku, setField, validateField]);

    const handleRejectSuggestion = useCallback(() => {
        setShowSkuSuggestion(false);
    }, []);

    const handleSlugChange = useCallback((newSlug: string) => {
        setField('slug', newSlug);
        setTouched(prev => ({ ...prev, slug: true }));
        validateField('slug', newSlug);
    }, [setField, validateField]);

    return (
        <>
            {/* ── Información básica ── */}
            <fieldset className={styles.fieldset}>
                <legend className={styles.legend}>Información básica</legend>

                <div className={styles.row}>
                    <div className={styles.field}>
                        <label className={styles.label} htmlFor="product-name">Nombre *</label>
                        <input
                            className={`${styles.input} ${touched.name && localErrors.name ? styles.inputError : ''}`}
                            id="product-name"
                            value={form.name}
                            onChange={e => handleNameChange(e.target.value)}
                            onBlur={() => handleBlur('name')}
                            required
                        />
                        {touched.name && (
                            <ValidationHelper
                                error={localErrors.name}
                                success={!!(form.name.trim().length > 0 && !localErrors.name)}
                                showProgress={form.name.length > 0}
                                progressValue={nameQualityScore}
                                progressLabel="Calidad SEO"
                            />
                        )}
                    </div>

                    <div className={styles.field}>
                        <label className={styles.label} htmlFor="product-sku">SKU</label>
                        <input
                            className={styles.input}
                            id="product-sku"
                            value={form.sku}
                            onChange={e => {
                                setField('sku', e.target.value);
                                setSkuAutoGenerated(false);
                                validateField('sku', e.target.value);
                            }}
                            onBlur={() => handleBlur('sku')}
                            placeholder={suggestedSku}
                        />
                        {!form.sku && showSkuSuggestion && form.name.trim() && (
                            <SkuSuggestion
                                suggestedSku={suggestedSku}
                                onAccept={handleAcceptSuggestion}
                                onReject={handleRejectSuggestion}
                            />
                        )}
                        {touched.sku && (
                            <ValidationHelper
                                error={localErrors.sku}
                                success={!!(form.sku && !localErrors.sku)}
                                hint={!localErrors.sku && !form.sku ? 'Ingresa un SKU único' : undefined}
                            />
                        )}
                    </div>
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-slug">Slug (URL amigable)</label>
                    <input
                        className={styles.input}
                        id="product-slug"
                        value={form.slug}
                        onChange={e => handleSlugChange(e.target.value)}
                        onBlur={() => handleBlur('slug')}
                        placeholder="se-genera-automaticamente"
                    />
                    {touched.slug && (
                        <ValidationHelper
                            error={localErrors.slug}
                            success={!!(form.slug && !localErrors.slug)}
                        />
                    )}
                    {form.slug && (
                        <SlugPreview slug={form.slug} originalName={form.name} />
                    )}
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-short-desc">Descripción corta</label>
                    <input
                        className={styles.input}
                        id="product-short-desc"
                        value={form.shortDescription}
                        onChange={e => setField('shortDescription', e.target.value)}
                        maxLength={160}
                    />
                    <span className={styles.fieldHint}>
                        {form.shortDescription.length}/160 caracteres
                        {form.shortDescription.length >= 120 && form.shortDescription.length <= 160 && ' ✓'}
                    </span>
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-desc">Descripción completa</label>
                    <textarea
                        className={styles.textarea}
                        id="product-desc"
                        rows={5}
                        value={form.description}
                        onChange={e => setField('description', e.target.value)}
                    />
                    <span className={styles.fieldHint}>
                        {form.description.length} caracteres
                    </span>
                </div>
            </fieldset>

            {/* ── Etiquetas ── */}
            <fieldset className={styles.fieldset}>
                <legend className={styles.legend}>Etiquetas</legend>
                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-tags">Agregar etiqueta</label>
                    <div className={styles.tagRow}>
                        <input
                            className={styles.input}
                            id="product-tags"
                            value={tagInput}
                            onChange={e => setTagInput(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), onAddTag())}
                            placeholder="Ej: destacado, oferta, nuevo..."
                        />
                        <button type="button" className={styles.addBtn} onClick={onAddTag}>＋</button>
                    </div>
                    {form.tags.length > 0 && (
                        <div className={styles.tags}>
                            {form.tags.map(t => (
                                <span key={t} className={styles.tag}>
                                    {t}
                                    <button
                                        type="button"
                                        onClick={() => onRemoveTag(t)}
                                        className={styles.tagRemove}
                                        aria-label={`Eliminar etiqueta ${t}`}
                                    >
                                        ✕
                                    </button>
                                </span>
                            ))}
                        </div>
                    )}
                </div>
            </fieldset>

            {/* ── Características ── */}
            <fieldset className={styles.fieldset}>
                <legend className={styles.legend}>Características</legend>
                <div className={styles.tagRow}>
                    <input
                        className={styles.input}
                        value={featureInput}
                        onChange={e => setFeatureInput(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), onAddFeature())}
                        placeholder="Ej: Material: acero inoxidable"
                    />
                    <button
                        type="button"
                        className={styles.addBtn}
                        onClick={onAddFeature}
                        aria-label="Agregar característica"
                    >
                        ＋
                    </button>
                </div>
                {(form.features ?? []).length > 0 && (
                    <ul className={styles.featureList}>
                        {(form.features ?? []).map((f, i) => (
                            <li key={i} className={styles.featureItem}>
                                <span>{f}</span>
                                <button
                                    type="button"
                                    onClick={() => onRemoveFeature(i)}
                                    className={styles.tagRemove}
                                    aria-label={`Eliminar característica ${f}`}
                                >
                                    ✕
                                </button>
                            </li>
                        ))}
                    </ul>
                )}
            </fieldset>
        </>
    );
});