import { forwardRef, useImperativeHandle, useState, useCallback, useMemo } from 'react';
import type { TabBasicoProps } from '../components/types';
import {
    generateSlug,
    generateSkuSuggestion,
    getInlineFieldError,
    calculateNameQualityScore,
} from '../../../../utils/productFormUtils';
import { ValidationHelper, SkuSuggestion } from '../components/ValidationHelper';
import styles from '../AdminProductFormPage.module.css';

export type TabBasicoRef = {
    validate: () => Record<string, string>;
};

export const TabBasico = forwardRef<TabBasicoRef, TabBasicoProps>(function TabBasico({
    form,
    errors = {},
    setField,
    tagInput,
    setTagInput,
    featureInput,
    setFeatureInput,
    onAddTag,
    onRemoveTag,
    onAddFeature,
    onRemoveFeature,
}, ref) {
    const [localErrors, setLocalErrors] = useState<Record<string, string>>(errors);
    const [touched, setTouched] = useState<Record<string, boolean>>({});
    const [showSkuSuggestion, setShowSkuSuggestion] = useState(false);
    const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);

    useImperativeHandle(ref, () => ({
        validate: () => {
            const errs: Record<string, string> = {};
            if (!form.name.trim()) errs.name = 'El nombre es obligatorio';
            setLocalErrors(errs);
            return errs;
        }
    }), [form]);

    const validateField = useCallback((fieldName: string, value: unknown) => {
        const error = getInlineFieldError(value, fieldName);
        setLocalErrors(prev => {
            if (error) {
                return { ...prev, [fieldName]: error };
            }
            const next = { ...prev };
            delete next[fieldName];
            return next;
        });
    }, []);

    const handleNameChange = useCallback((newName: string) => {
        setField('name', newName);
        validateField('name', newName);

        if (!form.slug || !touched.slug) {
            const autoSlug = generateSlug(newName);
            setField('slug', autoSlug);
        }

        if (!skuAutoGenerated && newName.trim()) {
            setShowSkuSuggestion(true);
        }
    }, [form.slug, skuAutoGenerated, touched.slug, setField, validateField]);

    const handleBlur = useCallback((fieldName: string) => {
        setTouched(prev => ({ ...prev, [fieldName]: true }));
    }, []);

    const suggestedSku = useMemo(
        () => generateSkuSuggestion(form.name, form.category?.name || 'PROD'),
        [form.name, form.category?.name]
    );

    const nameQualityScore = useMemo(
        () => calculateNameQualityScore(form.name),
        [form.name]
    );

    const handleAcceptSuggestion = useCallback(() => {
        setField('sku', suggestedSku);
        setSkuAutoGenerated(true);
        setShowSkuSuggestion(false);
        validateField('sku', suggestedSku);
    }, [suggestedSku, setField, validateField]);

    const handleRejectSuggestion = useCallback(() => {
        setShowSkuSuggestion(false);
    }, []);

    const handleSlugChange = useCallback((newSlug: string) => {
        setField('slug', newSlug);
        setTouched(prev => ({ ...prev, slug: true }));
        validateField('slug', newSlug);
    }, [setField, validateField]);

    const toggleTag = useCallback((tag: string, checked: boolean) => {
        const nextTags = checked
            ? (form.tags.includes(tag) ? form.tags : [...form.tags, tag])
            : form.tags.filter(t => t !== tag);
        setField('tags', nextTags);
    }, [form.tags, setField]);

    const handleFeaturedToggle = useCallback((checked: boolean) => {
        setField('isFeatured', checked);
        if (checked) {
            toggleTag('destacado', true);
        } else {
            toggleTag('destacado', false);
        }
    }, [setField, toggleTag]);

    return (
        <>
            <style>{`
                /* Mejoras de ergonomía táctil para móvil */
                .touchableCheckboxRow {
                    display: flex;
                    align-items: center;
                    min-height: 48px;
                    cursor: pointer;
                    padding: 0 8px;
                    margin: 4px 0;
                    border-radius: 8px;
                    transition: background-color 0.2s;
                }
                .touchableCheckboxRow:active {
                    background-color: rgba(255, 255, 255, 0.05);
                }
                .touchableCheckboxRow input[type="checkbox"] {
                    width: 22px;
                    height: 22px;
                    margin-right: 12px;
                    accent-color: var(--color-primary);
                    cursor: pointer;
                }
                .touchableCheckboxRow label {
                    flex: 1;
                    cursor: pointer;
                    user-select: none;
                    font-size: 15px;
                    color: var(--color-text-primary);
                }
                
                /* Botones de acción primarios (+) */
                .primaryActionBtn {
                    min-width: 44px !important;
                    min-height: 44px !important;
                    background-color: var(--color-primary) !important;
                    color: white !important;
                    border: none !important;
                    border-radius: 8px !important;
                    display: flex !important;
                    align-items: center !important;
                    justify-content: center !important;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1) !important;
                }
                .primaryActionBtn i {
                    font-size: 1.2rem;
                }
            `}</style>

            <fieldset className={styles.fieldset}>
                <div className={styles.row}>
                    <div className={styles.field}>
                        <label className={styles.label} htmlFor="product-name">Nombre *</label>
                        <input
                            className={`${styles.input} ${touched.name && localErrors.name ? styles.inputError : ''}`}
                            id="product-name"
                            value={form.name}
                            onChange={e => handleNameChange(e.target.value)}
                            onBlur={() => handleBlur('name')}
                            required
                            placeholder='Escriba un producto'
                            style={{ minHeight: '44px', fontSize: '16px' }}
                        />
                        {touched.name && (
                            <ValidationHelper
                                error={localErrors.name}
                                success={!!(form.name.trim().length > 0 && !localErrors.name)}
                                showProgress={form.name.length > 0}
                                progressValue={nameQualityScore}
                                progressLabel="Calidad SEO"
                            />
                        )}
                    </div>

                    <div className={styles.field}>
                        <label className={styles.label} htmlFor="product-sku">SKU</label>
                        <input
                            className={styles.input}
                            id="product-sku"
                            value={form.sku}
                            onChange={e => {
                                setField('sku', e.target.value);
                                setSkuAutoGenerated(false);
                                validateField('sku', e.target.value);
                            }}
                            onBlur={() => handleBlur('sku')}
                            placeholder={suggestedSku}
                            style={{ minHeight: '44px', fontSize: '16px' }}
                        />
                        {!form.sku && showSkuSuggestion && form.name.trim() && (
                            <SkuSuggestion
                                suggestedSku={suggestedSku}
                                onAccept={handleAcceptSuggestion}
                                onReject={handleRejectSuggestion}
                            />
                        )}
                        {touched.sku && (
                            <ValidationHelper
                                error={localErrors.sku}
                                success={!!(form.sku && !localErrors.sku)}
                                hint={!localErrors.sku && !form.sku ? 'Ingresa un SKU único' : undefined}
                            />
                        )}
                    </div>
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-slug">Slug (URL amigable)</label>
                    <input
                        className={styles.input}
                        id="product-slug"
                        value={form.slug}
                        onChange={e => handleSlugChange(e.target.value)}
                        onBlur={() => handleBlur('slug')}
                        placeholder="Se genera automáticamente a partir del nombre"
                        style={{ minHeight: '44px', fontSize: '16px' }}
                    />
                    {touched.slug && (
                        <ValidationHelper
                            error={localErrors.slug}
                            success={!!(form.slug && !localErrors.slug)}
                        />
                    )}
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-short-desc">Descripción corta</label>
                    <input
                        className={styles.input}
                        id="product-short-desc"
                        value={form.shortDescription}
                        onChange={e => setField('shortDescription', e.target.value)}
                        maxLength={160}
                        style={{ minHeight: '44px', fontSize: '16px' }}
                    />
                    <span className={styles.fieldHint}>
                        {form.shortDescription.length}/160 caracteres
                        {form.shortDescription.length >= 120 && form.shortDescription.length <= 160 && ' ✓'}
                    </span>
                </div>

                <div className={styles.field}>
                    <label className={styles.label} htmlFor="product-desc">Descripción completa</label>
                    <textarea
                        className={styles.textarea}
                        id="product-desc"
                        rows={5}
                        value={form.description}
                        onChange={e => setField('description', e.target.value)}
                        placeholder='Descripción del producto (opcional)'
                        style={{ fontSize: '16px', minHeight: '100px' }}
                    />
                    <span className={styles.fieldHint}>
                        {form.description.length} caracteres
                    </span>
                </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
                <legend className={styles.legend}>Etiquetas</legend>
                <div className={styles.field}>
                    
                    <label className="touchableCheckboxRow">
                        <input
                            type="checkbox"
                            checked={form.tags.includes('oferta')}
                            onChange={(e) => toggleTag('oferta', e.target.checked)}
                        />
                        <span>En Oferta</span>
                    </label>
                    
                    <label className="touchableCheckboxRow">
                        <input
                            type="checkbox"
                            checked={form.tags.includes('novedad')}
                            onChange={(e) => toggleTag('novedad', e.target.checked)}
                        />
                        <span>Novedad</span>
                    </label>
                    
                    <label className="touchableCheckboxRow">
                        <input
                            type="checkbox"
                            checked={form.isFeatured || false}
                            onChange={(e) => handleFeaturedToggle(e.target.checked)}
                        />
                        <span>Producto Destacado</span>
                    </label>

                    <div className={styles.tagRow} style={{ marginTop: '12px' }}>
                        <input
                            className={styles.input}
                            id="product-tags"
                            value={tagInput}
                            onChange={e => setTagInput(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), onAddTag())}
                            placeholder="Ej: destacado, oferta, nuevo..."
                            style={{ minHeight: '44px', fontSize: '16px' }}
                        />
                        <button type="button" className="primaryActionBtn" onClick={onAddTag} aria-label="Agregar etiqueta">
                            <i className="bi bi-plus-lg"></i>
                        </button>
                    </div>
                    {form.tags.length > 0 && (
                        <div className={styles.tags}>
                            {form.tags.map(t => (
                                <span key={t} className={styles.tag}>
                                    {t}
                                    <button
                                        type="button"
                                        onClick={() => onRemoveTag(t)}
                                        className={styles.tagRemove}
                                        aria-label={`Eliminar etiqueta ${t}`}
                                    >
                                        <i className="bi bi-x"></i>
                                    </button>
                                </span>
                            ))}
                        </div>
                    )}
                </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
                <legend className={styles.legend}>Características</legend>
                <div className={styles.tagRow}>
                    <input
                        className={styles.input}
                        value={featureInput}
                        onChange={e => setFeatureInput(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), onAddFeature())}
                        placeholder="Ej: Material: acero inoxidable"
                        style={{ minHeight: '44px', fontSize: '16px' }}
                    />
                    <button
                        type="button"
                        className="primaryActionBtn"
                        onClick={onAddFeature}
                        aria-label="Agregar característica"
                    >
                        <i className="bi bi-plus-lg"></i>
                    </button>
                </div>
                {(form.features ?? []).length > 0 && (
                    <ul className={styles.featureList}>
                        {(form.features ?? []).map((f, i) => (
                            <li key={i} className={styles.featureItem}>
                                <span>{f}</span>
                                <button
                                    type="button"
                                    onClick={() => onRemoveFeature(i)}
                                    className={styles.tagRemove}
                                    aria-label={`Eliminar característica ${f}`}
                                >
                                    <i className="bi bi-x"></i>
                                </button>
                            </li>
                        ))}
                    </ul>
                )}
            </fieldset>
        </>
    );
});